In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.DataFrame({"k1":["one","two"]*3 +["two"],"k2":[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [4]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [5]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [7]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [8]:
data.drop_duplicates(subset= ["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [9]:
data.drop_duplicates(subset= ["k1"],keep = "last")

k1  k2  v1
4  one   3   4
6  two   4   6

In [10]:
data.drop_duplicates(subset= ["k1","k2"],keep = "last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [11]:
data = pd.DataFrame({"food":["Bacon","pulled_pork","bacon","pastrami","corned beef","bacon","Pastrami","honey ham","nova box"],"ounces":[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        Bacon     4.0
1  pulled_pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     Pastrami     3.0
7    honey ham     5.0
8     nova box     6.0

In [13]:
meat_to_animal = {"bacon":"pig","pulled_pork":"pig","pastrami":"cow","corned beef":"cow","honey ham":"pig","nova box":"salmon"}
data["animal"]= data["food"].map(meat_to_animal)
data

food  ounces  animal
0        Bacon     4.0     NaN
1  pulled_pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     Pastrami     3.0     NaN
7    honey ham     5.0     pig
8     nova box     6.0  salmon

In [15]:
lowercased = data["food"].str.lower()
data["animal"] = lowercased.map(meat_to_animal)
data


food  ounces  animal
0        Bacon     4.0     pig
1  pulled_pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     Pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova box     6.0  salmon

In [17]:
data["food"].map(lambda x: meat_to_animal[x.lower()])
data

food  ounces  animal
0        Bacon     4.0     pig
1  pulled_pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     Pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova box     6.0  salmon

In [18]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [19]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace([-999,-1000])

0    1.0
1    1.0
2    2.0
3    2.0
4    2.0
5    3.0
dtype: float64

In [22]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [23]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [25]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [28]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=["Ohio", "Colorado", "New York"],columns=["one", "two", "three", "four"]) 
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [29]:
transform = lambda x: x[:4].upper() 
data.index.map(transform) 

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [30]:
data.index = data.index.map(transform) 
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [31]:
data.rename(index=str.title, columns=str.upper) 

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [32]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"}) 

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [33]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data.rename(columns={"three": "peekaboo"}, inplace=True) 
data 

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [34]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
ages 

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [35]:
bins = [18, 25, 35, 60, 100] 
age_categories = pd.cut(ages, bins) 
age_categories 

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [36]:
print(age_categories.codes) # age_categories.codes 
age_categories.categories #age_categories. categories[3] 

[0 0 0 1 0 0 2 1 3 2 2 1]


IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [37]:
pd.value_counts(age_categories) 

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [38]:
age_categories = pd.cut(ages, bins,right=False)
age_categories 

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [40]:
age_categories.codes 

array([0, 0, 1, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [41]:
group_names = ["Youth", "VoungAdult", "MiddleAged", "Senior"] 
pd.cut(ages, bins, labels=group_names) 

['Youth', 'Youth', 'Youth', 'VoungAdult', 'Youth', ..., 'VoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'VoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'VoungAdult' < 'MiddleAged' < 'Senior']

In [42]:
data = np.random.uniform(size=20)
data 

array([0.55637461, 0.07629717, 0.38798279, 0.27303613, 0.50276745,
       0.98588142, 0.20167982, 0.14679338, 0.43100903, 0.76748976,
       0.92951953, 0.81580003, 0.50676949, 0.67950998, 0.38403372,
       0.63371206, 0.84729352, 0.03285021, 0.14765931, 0.5382028 ])

In [45]:
bin = pd.cut(data, 4, precision=2) 
bin 

[(0.51, 0.75], (0.032, 0.27], (0.27, 0.51], (0.27, 0.51], (0.27, 0.51], ..., (0.51, 0.75], (0.75, 0.99], (0.032, 0.27], (0.032, 0.27], (0.51, 0.75]]
Length: 20
Categories (4, interval[float64, right]): [(0.032, 0.27] < (0.27, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [44]:
bin.codes
pd.value_counts(bin) 

(0.27, 0.51]     6
(0.032, 0.27]    5
(0.75, 0.99]     5
(0.51, 0.75]     4
Name: count, dtype: int64

In [47]:
data = np.random.standard_normal(1000) # Normally distributed 
quartiles = pd.qcut(data, 4, precision=2) # Cut into quartiles , precision=2 
quartiles 

[(-0.65, -0.019], (-3.1399999999999997, -0.65], (0.67, 3.61], (-0.019, 0.67], (-3.1399999999999997, -0.65], ..., (-0.019, 0.67], (-0.65, -0.019], (-0.019, 0.67], (0.67, 3.61], (0.67, 3.61]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.1399999999999997, -0.65] < (-0.65, -0.019] < (-0.019, 0.67] < (0.67, 3.61]]

In [49]:
pd.value_counts(quartiles) 

(-3.1399999999999997, -0.65]    250
(-0.65, -0.019]                 250
(-0.019, 0.67]                  250
(0.67, 3.61]                    250
Name: count, dtype: int64

In [50]:
data = pd.DataFrame(np.random.standard_normal((1000, 4))) #DataFrame called data with 1060 rows 

In [51]:
data.describe() 

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.031630     0.005546     0.023948    -0.025035
std       1.032358     0.996169     0.992638     0.997733
min      -3.049105    -3.398622    -2.634298    -3.046623
25%      -0.700685    -0.678340    -0.695387    -0.666704
50%      -0.036735     0.038227     0.015725    -0.028954
75%       0.635413     0.685710     0.719569     0.607450
max       3.115294     3.156676     2.949446     2.738893

In [53]:
col = data[2]
col[col.abs() > 3] 

Series([], Name: 2, dtype: float64)

In [54]:
data[(data.abs() > 3).any(axis="columns")] 

0         1         2         3
153 -3.049105 -0.009724  0.514363  0.719492
335  0.112866 -3.053051  0.092290  0.508561
369  2.102749  3.156676 -2.072431  0.583455
878  3.115294  0.011665 -1.238460 -0.995334
883 -0.781103 -0.031262  0.159554 -3.046623
951 -0.396513 -3.398622  0.571205 -2.504084

In [55]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe() 

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.031696     0.005841     0.023948    -0.024989
std       1.031870     0.994238     0.992638     0.997592
min      -3.000000    -3.000000    -2.634298    -3.000000
25%      -0.700685    -0.678340    -0.695387    -0.666704
50%      -0.036735     0.038227     0.015725    -0.028954
75%       0.635413     0.685710     0.719569     0.607450
max       3.000000     3.000000     2.949446     2.738893

In [56]:
np.sign(data).head() 

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2  1.0 -1.0 -1.0 -1.0
3  1.0  1.0 -1.0  1.0
4 -1.0  1.0 -1.0 -1.0

In [57]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7))) 

In [58]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [59]:
sampler = np.random.permutation(5) 
sampler 

array([4, 1, 0, 3, 2])

In [60]:
df.take(sampler) 

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [61]:
column_sampler = np.random.permutation(7)
column_sampler 

array([1, 0, 2, 4, 3, 6, 5])

In [62]:
df.take(column_sampler, axis="columns") 

1   0   2   4   3   6   5
0   1   0   2   4   3   6   5
1   8   7   9  11  10  13  12
2  15  14  16  18  17  20  19
3  22  21  23  25  24  27  26
4  29  28  30  32  31  34  33

In [63]:
df.sample(n=3) 

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [64]:
choices = pd.Series([5, 7, -1, 6, 4]) 
choices. sample(n=10, replace=True) 

4    4
0    5
4    4
0    5
0    5
0    5
4    4
3    6
1    7
0    5
dtype: int64

In [65]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [66]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [67]:
pd.get_dummies(df["key"], dtype=float) 

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [71]:
dummies = pd.get_dummies(df["key"], prefix = "key", dtype=float)  
df_with_dummy = df[["data1"]].join(dummies) 
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0